from . import res_config_settings
from . import delivery_carrier
from . import cargoson_request
from . import stock_picking
from . import sale_order
from . import product
from . import cargoson_courier
from . import cargoson_channel
from . import stock_package_type
